## Question 1
### Write a python program to reverse array elements. Use an array of integers of size 10 elements. Do reverse operation without using the inbuilt function.

In [2]:
l = [10, 3, 78, 45, 101, 23, 48, 47, 61, 200]
a = []
b = 0
for j in l: # for calculating lenght of given array
    b = b+1

for i in range(b-1, -1, -1):
    a = a + [l[i]]

print(f"New reversed array is {a}")

New reversed array is [200, 61, 47, 48, 23, 101, 45, 78, 3, 10]


## Question 2 

### Write a python program to transpose a matrix of size 3 X 4. Perform transpose operation without using the inbuilt function

In [8]:
import numpy as np
a = np.array([i for i in range(1,13)],dtype="i").reshape(4,3)
l = np.zeros((3,4),dtype="i")
for i in range(3):
    for j in range(4):
        l[i][j]=a[j][i]

print("Your matrix :")
print(a)
print()
print("Transpose of ur matrix is : ")
print(l)

Your matrix :
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Transpose of ur matrix is : 
[[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]


## Question 3

### Write a python program that takes a 3X3 matrix as input and prints only the matrix's lower triangular part. Perform this task without using the inbuilt function.

In [10]:
import numpy as np
a = np.array([i for i in range(1,10)],dtype="i").reshape(3,3)
print("Lower Triangular part is :")
print([a[0][0]])
print([a[1][0],a[1][1]])
print([a[2][0],a[2][1],a[2][2]])

Lower Triangular part is :
[1]
[4, 5]
[7, 8, 9]
