# $Matrix$ $Multiplication$ $program$

In [3]:
import numpy as np

try :
    o1 = eval(input("Enter order of ur 1st matrix (as a list) like '[no. of rows, no. of columns]' :"))
    a = eval(input("Enter ur 1st matrix as array : "))
    b = np.array(a,dtype="i").reshape(o1[0],o1[1])

    o2 = eval(input("Enter order of ur 2nd matrix (as a list) like '[no. of rows, no. of columns]' :"))
    c = eval(input("Enter ur 2nd matrix as array : "))
    d = np.array(c,dtype="i").reshape(o2[0],o2[1])

    e = np.zeros((o1[0],o2[1]),dtype="i")

    if o1[1]==o2[0]: # column of 1st marix and row of 2nd matrix should be same for multiply
        for i in range(len(b)): # in range have to take no. of rows of 1st matrix i.e. b
            for j in range(len(d[0])): # in range have to take no. of columns of 2nd matrix
                for k in range(len(d)): # in range , no. of rows of 2nd matrix
                    e[i][j] += b[i][k]*d[k][j]
        
        print("XXXXXXXXXXXXXXXXXXXXXXXXXXX")
        print(" ")
        print("1st Matrix :")
        print(b)
        print(" ")
        print("XXXXXXXXXXXXXXXXXXXXXXXXXXX")
        print(" ")
        print("2nd Matrix :")
        print(d)
        print(" ")
        print("XXXXXXXXXXXXXXXXXXXXXXXXXXX")
        print(" ")
        print("After Multiplication :")
        print(e)
        print(" ")
        print("XXXXXXXXXXXXXXXXXXXXXXXXXXX")


except Exception as x:
    print("your matrix does not match it's size")
    print("error is ",x)


XXXXXXXXXXXXXXXXXXXXXXXXXXX
 
1st Matrix :
[[1 2]
 [0 1]
 [1 4]
 [2 3]]
 
XXXXXXXXXXXXXXXXXXXXXXXXXXX
 
2nd Matrix :
[[0 1 2 1]
 [1 0 2 2]]
 
XXXXXXXXXXXXXXXXXXXXXXXXXXX
 
After Multiplication :
[[ 2  1  6  5]
 [ 1  0  2  2]
 [ 4  1 10  9]
 [ 3  2 10  8]]
 
XXXXXXXXXXXXXXXXXXXXXXXXXXX


# Matrix Addition Program 

In [16]:
import numpy as np

try :
    o1 = eval(input("Enter order of ur 1st matrix (as a list) in the form of [row,column]:"))
    a = eval(input("Enter ur 1st matrix as array"))
    b = np.array(a,dtype="i").reshape(o1[0],o1[1])
    
    o2 = eval(input("Enter order of ur 2nd matrix (as a list) in the form of [row,column]:"))
    c = eval(input("Enter ur 2nd matrix as array"))
    d = np.array(c,dtype="i").reshape(o2[0],o2[1])
    
    e = []
    if o1==o2:
        e = b + d

        print("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
        print("1st Matrix :")
        print(b)
        print("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
        print("2nd Matrix :")
        print(d)
        print("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
        print("After Addition :")
        print(e)
        print("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")

        
except Exception as x:
    print("your matrix doesnot match it's size")
    print("error is ",x)

1st Matrix :
[[1 2]
 [3 4]]
2nd Matrix :
[[5 6]
 [7 8]]
After Addition :
[[ 6  8]
 [10 12]]
